#!/bin/bash
set -e

rm -rf .git
git init
git commit --allow-empty -m 'Initial commit'
git add .
git commit -m 'Initial project structure'
cp local.yaml.example local.yaml
make build
make run
rm init-new-project
